### ISSUE TITLE
Releases / Downloads?

### ISSUE THREAD

**Issue by tjreigh** [suvanl/TVVC#2]
I've been looking through some of your work and this really caught my eyes. This looks like quite a cool app, but as much as I would like to try it, there's no instructions on how to use it for myself? I would like a download link with an exe or maybe some installation instructions because this seems like a cool idea. Thoughts?

**Comment by suvanl** [comment]
Hey! I initially created this repository for the purpose of having somewhere to have the source code for this project in case it were to get lost from my local machine for any reason, hence why there is no executable download or installation instructions at the moment.

However, now that you've mentioned it, and seem to be interested in it, I'll create an installer as well as installation instructions, within the next few days or so. 👌

**Comment by tjreigh** [comment]
Sounds great! Keep me posted! I found you through the explore tab and your delet bot, but your work seems really cool and I'd like to see what this app can do.

**Comment by suvanl** [comment]
That's pretty cool! delet is one of my main projects so I'm glad you found it.

Version 1.0.0 of TVVC has now been released, and installation instructions can be found in the [README file](https://github.com/suvanl/TVVC/blob/master/README.md).
If you come across any bugs/issues, feel free to create a new issue.

Thanks again for creating this issue and requesting a release!
